Testing using larger runner
usdot-fhwa-stol/carma-msgs pull request #237
Opened 2024-04-30 14:46 UTC by paulbourelly999

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-30 15:40 UTC, MishkaMN requested changes

2024-04-30 15:40 UTC, MishkaMN commented on .github/workflows/docker.yml
> +      runner: ubuntu-latest-16-cores
we should definitely include the big runner in dockerhub.yml as well

2024-04-30 21:47 UTC, MishkaMN approved these changes

2024-05-05 14:22 UTC, JonSmet approved these changes

2024-05-06 13:44 UTC, merged